// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CompareOverlay: typeof import('./src/components/CompareOverlay.vue')['default']
    ComponentOverlay: typeof import('./src/components/ComponentOverlay.vue')['default']
    copy: typeof import('./src/components/ComponentOverlay copy.vue')['default']
    FilterStep: typeof import('./src/components/FilterStep.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/ic/on-bx-bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/ic/on-bx-bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/ic/on-akar-icons-github-fill')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    'MdiAccount-': typeof import('~icons/mdi/account-')['default']
    MdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    MdiBorderAllVariant: typeof import('~icons/mdi/border-all-variant')['default']
    MdiBorderBottom: typeof import('~icons/mdi/border-bottom')['default']
    MdiBorderHorizontal: typeof import('~icons/mdi/border-horizontal')['default']
    MdiBorderInside: typeof import('~icons/mdi/border-inside')['default']
    MdiBorderOutside: typeof import('~icons/mdi/border-outside')['default']
    MdiBorderVertical: typeof import('~icons/mdi/border-vertical')['default']
    MdiBox: typeof import('~icons/mdi/box')['default']
    MdiChartBar: typeof import('~icons/mdi/chart-bar')['default']
    MdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiChevrotRight: typeof import('~icons/mdi/chevrot-right')['default']
    MdiCrane: typeof import('~icons/mdi/crane')['default']
    MdiCrosshairsGps: typeof import('~icons/mdi/crosshairs-gps')['default']
    MdiDownload: typeof import('~icons/mdi/download')['default']
    MdiEarth: typeof import('~icons/mdi/earth')['default']
    MdiFactory: typeof import('~icons/mdi/factory')['default']
    MdiFerry: typeof import('~icons/mdi/ferry')['default']
    MdiFlagOutline: typeof import('~icons/mdi/flag-outline')['default']
    MdiHammerWrench: typeof import('~icons/mdi/hammer-wrench')['default']
    MdiHomeVariantOutline: typeof import('~icons/mdi/home-variant-outline')['default']
    MdiHospitalBuilding: typeof import('~icons/mdi/hospital-building')['default']
    MdiHouse: typeof import('~icons/mdi/house')['default']
    MdiMenuDown: typeof import('~icons/mdi/menu-down')['default']
    MdiOfficeBuildingOutline: typeof import('~icons/mdi/office-building-outline')['default']
    MdiScaleUnbalanced: typeof import('~icons/mdi/scale-unbalanced')['default']
    MdiSchool: typeof import('~icons/mdi/school')['default']
    MdiShip: typeof import('~icons/mdi/ship')['default']
    MdiStore: typeof import('~icons/mdi/store')['default']
    MdiTrain: typeof import('~icons/mdi/train')['default']
    MdiTruck: typeof import('~icons/mdi/truck')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
